### ISSUE TITLE
JC Penny

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#632] opened 2017-12-21 00:02 UTC
https://stores.jcpenney.com/tx/austin/clothing-stores-austin-tx-2884.html

**Comment by whoissteven** [comment] 2017-12-21 02:38
This is being done by someone else #602

**Comment by iandees** [comment] 2017-12-21 02:40
Dupe of #602.

**Closed by iandees** 2017-12-21 02:40 UTC

**Comment by evanmosseri** [comment] 2017-12-21 02:44
Oops, I'll delete those hours on my timesheet
