### ISSUE TITLE
Prestons (ZA) (shop/alcohol)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7051] opened 2024-02-08 11:36 UTC
### Brand name

Prestons

### Wikidata ID

Q116861728

### Store finder url(s)

https://prestonsliquors.co.za/store-locator/

**Comment by davidhicks** [comment] 2024-02-08 11:42
Thanks for adding.

Closed as a duplicate of #7027

**Closed by davidhicks** 2024-02-08 11:42 UTC
