### ISSUE TITLE
GeoJSON or CSV Output

### ISSUE THREAD

**Issue by justinelliotmeyers** [alltheplaces/alltheplaces#879] opened 2018-04-24 19:24 UTC
I am trying to bring in the raw current output into QGIS, but it doesn't like the format. I tried to add commas at the end of each line and enclose it in the http://geojson.io format, but QGIS still will not open the file. When I grab a small section of it, it handles it no problem. So I was hoping for a different output that qgis could handle a little better if possible.

Thanks!

**Comment by iandees** [comment] 2018-04-24 19:29
This is a dupe of #877 (I filed the issue this morning and worked on it a bit). The updated code is still generating a new file. When you see the file timestamp on the website go past March 26th it'll be the new format.

**Comment by iandees** [comment] 2018-04-25 17:03
The new output is a .tar.gz (like a zip file) of individual GeoJSON documents. Instead of one big long file that is hard to read or process, I left them separated out per spider. You should be able to load these all up in QGIS (or some of them in geojson.io) if you'd like.

Let me know if it doesn't work!

**Closed by iandees** 2018-04-25 17:03 UTC
