### ISSUE TITLE
scraperbot displays wrong number of extracted items

### ISSUE THREAD

**Issue by nicolas17** [alltheplaces/alltheplaces#396] opened 2017-12-12 22:01 UTC
As seen in #374, if a scraper extracts 5 items into the JSON, scraperbot says "Results: 4 items". This is because the JSON has one feature per line, but it doesn't have a newline at the end of the file, so `wc -l` outputs 4 even though the file has 5 lines.

Unfortunately this can't be fixed by simply adding 1 to FEATURE_COUNT, or adding a newline at the end of the file before passing it to `wc -l`, because then a JSON with no items found would be shown as 1. That's why I'm reporting a bug to let you decide the best way, instead of sending a trivial PR 😄

**Comment by iandees** [comment] 2017-12-12 22:03
Thanks! I noticed that too. I think I'm going to adjust the CI builder code to be a bit smarter about how it generates the comments.

**Comment by CloCkWeRX** [comment] 2024-08-04 23:37
Same as #1009 ?

**Comment by iandees** [comment] 2024-08-05 00:00
Dupe of #1009

**Closed by iandees** 2024-08-05 00:00 UTC
Labels: bug
